# Generated by Django 5.2.4 on 2025-07-23 20:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('Usuario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ssid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('url_api', models.CharField(max_length=100, unique=True)),
                ('autonomo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_core.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_recuperar',
            field=models.CharField(blank=True, default='sin cambios pendientes', max_length=254),
        ),
    ]
