# Generated by Django 5.2.4 on 2025-07-24 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_permisopersonalizado_red_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisopersonalizado',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=265)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=265)),
                ('mensaje', models.CharField(max_length=265)),
                ('fecha_hora', models.DateTimeField()),
                ('configuracion', models.CharField(max_length=265)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
